const Map<String, String> arStrings = {
  'appName': 'لينغو ليرن',
  'tagline': 'تعلّم. تدرّب. تطوّر.',

  'yourProgress': 'تقدّمك',
  'dailyLesson': 'درس اليوم',
  'noWordsAvailable': 'لا توجد كلمات',
  'continueNewWord': 'تابع تعلّم كلمة جديدة',
  'quickPractice': 'تدريب سريع',
  'vocabulary': 'المفردات',
  'quiz': 'اختبار',
  'favorites': 'المفضلة',
  'progress': 'التقدم',
  'testYourself': 'اختبر نفسك',

  'searchWords': 'ابحث عن كلمات...',
  'all': 'الكل',
  'addWord': 'إضافة كلمة',
  'editWord': 'تعديل كلمة',
  'deleteWord': 'حذف كلمة',
  'wordDetails': 'تفاصيل الكلمة',
  'word': 'الكلمة',
  'translation': 'الترجمة',
  'pronunciation': 'النطق',
  'example': 'مثال',
  'category': 'الفئة',
  'saveChanges': 'حفظ التغييرات',
  'cancel': 'إلغاء',
  'noWordsFound': 'لم يتم العثور على كلمات',
  'tryAnotherSearch': 'جرّب بحثاً أو فئة أخرى.',
  'markAsLearned': 'وضع علامة كمتعلّمة',
  'learned': 'تم التعلم',
  'greatJobLearned': 'أحسنت! لقد تعلمت هذه الكلمة 🎉',
  'edit': 'تعديل',
  'delete': 'حذف',

  'pleaseEnterWord': 'الرجاء إدخال الكلمة',
  'pleaseEnterTranslation': 'الرجاء إدخال الترجمة',
  'pleaseEnterPronunciation': 'الرجاء إدخال النطق',
  'pleaseEnterExample': 'الرجاء إدخال مثال',
  'pleaseEnterCategory': 'الرجاء إدخال الفئة',
  'hintWord': 'مثال: رائع',
  'hintTranslation': 'مثال: Amazing',
  'hintPronunciation': 'مثال: RAA-e3',
  'hintExample': 'مثال: هذه تجربة رائعة.',
  'hintCategory': 'مثال: كلمات شائعة',

  'deleteWordMessage': 'لا يمكن التراجع عن هذا الإجراء.',

  'practiceQuiz': 'اختبار تدريبي',
  'chooseCategory': 'اختر الفئة',
  'whatToPractice': 'ماذا تريد أن تتدرب عليه؟',
  'allCategories': 'جميع الفئات',
  'chooseQuizLength': 'طول الاختبار',
  'howManyQuestions': 'كم عدد الأسئلة؟',
  'allQuestions': 'جميع الأسئلة',
  'whatIsTheMeaning': 'ما معنى:',
  'chooseCorrectAnswer': 'اختر الإجابة الصحيحة:',
  'nextQuestion': 'السؤال التالي',
  'showResult': 'عرض النتيجة',
  'quizCompleted': 'اكتمل الاختبار!',
  'tryAgain': 'حاول مرة أخرى',
  'done': 'تم',
  'noWordsForQuiz': 'لا توجد كلمات',
  'addWordsBeforeQuiz': 'أضف بعض المفردات قبل بدء الاختبار.',
  'excellent': 'ممتاز! أنت رائع! 🎉',
  'greatJob': 'أحسنت! استمر في التدرب! 👏',
  'goodEffort': 'جهد جيد! مزيد من التدرب سيساعدك.',
  'keepPracticing': 'استمر في التدرب وستتحسن! 💪',

  'noFavoritesYet': 'لا توجد مفضلات بعد',
  'saveFavoriteWords': 'احفظ كلماتك المفضلة لمراجعتها لاحقاً.',
  'browseVocabulary': 'تصفح المفردات',

  'myProgress': 'تقدّمي',
  'learningProgress': 'تقدم التعلّم',
  'totalWords': 'إجمالي الكلمات',
  'quizzes': 'الاختبارات',
  'quizPerformance': 'أداء الاختبارات',
  'bestScore': 'أفضل نتيجة',
  'lastScore': 'آخر نتيجة',
  'categories': 'الفئات',
  'takeFirstQuiz': 'قم بأول اختبار لرؤية أدائك هنا.',

  'settings': 'الإعدادات',
  'appearance': 'المظهر',
  'theme': 'السمة',
  'lightMode': 'فاتح',
  'darkMode': 'داكن',
  'systemDefault': 'النظام',
  'language': 'اللغة',
  'english': 'English',
  'arabic': 'العربية',
  'data': 'البيانات',
  'resetAppData': 'إعادة تعيين البيانات',
  'resetAppDataDesc': 'حذف تقدمك واستعادة الكلمات الافتراضية',
  'resetAppDataMessage':
      'سيتم حذف الكلمات المضافة والمفضلة وتقدم التعلم ونتائج الاختبارات. سيتم استعادة الكلمات الافتراضية.',
  'reset': 'إعادة تعيين',
  'dataResetSuccess': 'تم إعادة تعيين بيانات التطبيق بنجاح.',

  'buildVocabulary': 'ابنِ مفرداتك',
  'buildVocabularyDesc': 'تعلّم كلمات جديدة وابنِ مفرداتك خطوة بخطوة.',
  'practiceWithQuizzes': 'تدرّب بالاختبارات',
  'practiceWithQuizzesDesc': 'اختبر نفسك بالاختبارات وحسّن مهاراتك اللغوية.',
  'trackYourProgress': 'تابع تقدّمك',
  'trackYourProgressDesc': 'تتبع تقدمك في التعلم وشاهد تحسنك.',
  'getStarted': 'ابدأ الآن',
  'next': 'التالي',
  'skip': 'تخطي',

  'wordMarkedLearned': 'تم وضع علامة الكلمة كمتعلّمة! 🎉',
  'wordMarkedNotLearned': 'تم إزالة علامة التعلّم عن الكلمة.',

  'readyToContinue': 'مستعد لمتابعة التعلّم؟',

  'listen': 'استمع',
  'pronunciationUnavailable': 'النطق غير متاح لهذه اللغة.',

  'pronunciationPractice': 'تدريب النطق',
  'practicePronunciation': 'تدرّب على النطق',
  'pronunciationTip': 'استمع جيداً، ثم اضغط على المايك وقل الكلمة.',
  'tapToRecord': 'اضغط للتسجيل',
  'tapToStop': 'اضغط للإيقاف',
  'listening': 'جارٍ الاستماع...',
  'analyzingPronunciation': 'جارٍ تحليل النطق...',
  'excellentPronunciation': 'نطق ممتاز! 🎉',
  'greatPronunciation': 'نطق رائع!',
  'goodPronunciation': 'نطق جيد!',
  'needsPracticePronunciation': 'واصل التدريب – أنت تقترب!',
  'weHeard': 'تم التعرف على:',
  'nothingRecognized': 'لم نسمعك بوضوح. حاول مرة أخرى.',
  'focusSounds': 'أصوات تحتاج تركيزاً:',
  'nextWord': 'الكلمة التالية',
  'score': 'النتيجة',
  'speechNotAvailable': 'التعرف على الكلام غير متاح لهذه اللغة على جهازك.',
  'microphonePermissionDenied':
      'يلزم الوصول إلى الميكروفون لتدريب النطق. اسمح به من الإعدادات ثم أعد المحاولة.',
  'noSpeechDetected':
      'لم نتمكن من التقاط أي كلام. إذا كنت تستخدم محاكي أندرويد، تأكد من تفعيل الميكروفون ثم أعد المحاولة.',
  'speechNetworkError':
      'يتطلب التعرف على الكلام اتصالاً بالإنترنت. تحقق من شبكتك ثم أعد المحاولة.',
  'speechRecognitionFailed': 'فشل التعرف على الكلام. حاول مرة أخرى.',
  'speechInitializationTimedOut':
      'يستغرق تشغيل التعرف على الكلام وقتاً طويلاً. أعد المحاولة.',
  'recordingTooShort':
      'كانت المحاولة قصيرة جداً لالتقاط أي كلام. اضغط الزر لفترة أطول وحاول مرة أخرى.',
  'recordingFailed': 'تعذّر تسجيل محاولتك. تحقق من الميكروفون وحاول مرة أخرى.',

  'doesntSoundRight': 'النطق غير صحيح',
  'soundsGood': 'نطق سليم!',
  'matchLabel': 'المطابقة',
  'yourAttempt': 'محاولتك',
  'reference': 'النطق المرجعي',
  'segmentsCaption': 'ما تم التقاطه',
  'attemptAudioUnavailable': 'تسجيل محاولتك غير متاح على هذا الجهاز.',
  'accuracyScore': 'الدقة',
  'fluencyScore': 'السلاسة',
  'completenessScore': 'الاكتمال',
  'prosodyScore': 'النبرة',
  'soundAccuracyLegend': 'الأخضر ممتاز · الكهرماني قريب · الأحمر يحتاج تدريباً',
  'omissionTag': 'محذوف',
  'insertionTag': 'زائد',
  'mispronunciationTag': 'مختلف',
  'feedbackFocusPhonemes': 'ركّز على الأصوات المميزة وقارنها بالنطق المرجعي.',
  'feedbackOmission': 'حذفت جزءاً من الكلمة. انطق كل الأصوات.',
  'feedbackInsertion': 'أضفت صوتاً إضافياً. قل الكلمة فقط.',
  'feedbackWrongWord':
      'تعذر على المحرك مطابقة الكلمة. استمع إلى النطق المرجعي وحاول مرة أخرى.',
  'feedbackPhraseIncomplete':
      'تم التقاط جزء فقط من العبارة. قل العبارة كاملة هذه المرة.',
  'feedbackStart':
      'لم يتم التقاط بداية الكلمة بوضوح. استمع إلى النطق المرجعي وركّز على الجزء الأول.',
  'feedbackMiddle':
      'لم يتم التقاط وسط الكلمة بوضوح. استمع إلى النطق المرجعي وحاول مرة أخرى.',
  'feedbackEnd':
      'لم يتم التقاط نهاية الكلمة بوضوح. استمع إلى النطق المرجعي وركّز على الجزء الأخير.',
  'feedbackMismatch':
      'تم التقاط بعض الأصوات بشكل مختلف قليلاً. استمع إلى النطق المرجعي وحاول مرة أخرى.',
  'feedbackExtra': 'تم التقاط أصوات إضافية. حاول قول الكلمة فقط.',
  'feedbackClose':
      'قريب جداً! استمع إلى النطق المرجعي وحاول مرة أخرى بنطق أوضح.',
  'micUnavailable': 'لا يوجد ميكروفون على هذا الجهاز.',
  'audioTooQuiet':
      'كان التسجيل هادئاً جداً أو خالياً من كلام واضح. اقترب من الميكروفون وحاول مرة أخرى.',
  'unclearAudio': 'كان الصوت مليئاً بالضوضاء ليتسنى تقييمه. جرّب في مكان هادئ.',
  'invalidAudioFormat': 'تعذر معالجة التسجيل. حاول مرة أخرى.',
  'recordingClipped':
      'كان التسجيل مشوّشاً (صوته مرتفع جداً). أبعد الهاتف قليلاً وحاول مرة أخرى.',
  'preparingRecording': 'جارٍ تجهيز الميكروفون...',
  'recording': 'جارٍ التسجيل...',
  'howToProduceSound': 'كيف تُنتج هذا الصوت',
  'articulationTip':
      'استمع إلى النطق المرجعي وحاول تقليد طريقة تشكيل الصوت (اللسان والشفتان والفك).',
  'focusOnRetry': 'جرّب الآن مرة أخرى مع التركيز على الأصوات المميّزة.',
  'assessmentNetworkError':
      'يتطلب تقييم النطق اتصالاً بالإنترنت. تحقق من شبكتك ثم أعد المحاولة.',
  'assessmentUnavailable': 'تقييم النطق غير متاح مؤقتاً. حاول مرة أخرى.',
  'tokenFailed': 'تعذر الحصول على رمز وصول صالح للتقييم. حاول مرة أخرى.',
  'assessmentTimedOut':
      'استغرق التقييم وقتاً طويلاً. تحقق من اتصالك وحاول مرة أخرى.',
  'assessmentFailed': 'فشلت خدمة التقييم. حاول مرة أخرى.',
  'malformedResponse': 'كانت استجابة التقييم غير صالحة. حاول مرة أخرى.',

  'dictionary': 'القاموس',
  'searchAnyWord': 'ابحث عن أي كلمة إنجليزية',
  'searchingWord': 'جارٍ البحث…',
  'dictionaryHint':
      'ابحث عن أي كلمة إنجليزية وسيعرض لك لينغوليرن معناها ونطقها ومثالاً عليها وصوتها.',
  'meaning': 'المعنى',
  'wordNotFoundMessage':
      'لم يتم العثور على الكلمة. تحقق من التهجئة وحاول مرة أخرى.',
  'couldNotConnect': 'تعذّر الاتصال. تحقق من اتصالك بالإنترنت.',
  'dictionaryApiError': 'تعذّر تحميل معلومات الكلمة. حاول مرة أخرى.',
  'requestTimedOut':
      'تعذّر تحميل هذه الكلمة الآن. تحقق من الاتصال وحاول مرة أخرى.',
  'dictionaryInvalidResponse': 'استجابة غير متوقعة من خادم القاموس.',
  'saveWordFailed': 'تعذّر حفظ الكلمة. حاول مرة أخرى.',
  'recentSearches': 'عمليات البحث الأخيرة',
  'viewDetails': 'عرض التفاصيل',
  'addToMyWords': 'أضف إلى كلماتي',
  'removeFromMyWords': 'أزل من كلماتي',
  'wordAddedToMyWords': 'تمت إضافة الكلمة إلى كلماتك.',
  'sourceLabel': 'المصدر',
  'fetchWord': 'ابحث عن الكلمة',
  'fetchWordHint':
      'اكتب أي كلمة إنجليزية وسيقوم لينغوليرن بملء معناها ونطقها ومثالها وصوتها تلقائياً.',
  'autoFetched': 'تلقائي',

  'networkError': 'خطأ في الشبكة. تحقق من اتصالك بالإنترنت.',
  'unknownError': 'حدث خطأ غير متوقع. حاول مرة أخرى.',
  'retry': 'إعادة المحاولة',

  'login': 'تسجيل الدخول',
  'signUp': 'إنشاء حساب',
  'logout': 'تسجيل الخروج',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'confirmPassword': 'تأكيد كلمة المرور',
  'name': 'الاسم',
  'welcomeBack': 'مرحباً بعودتك!',
  'signInToContinue': 'سجّل الدخول لمتابعة التعلم.',
  'createAccount': 'إنشاء حساب',
  'joinLingoLearn': 'انضم إلى لينغو ليرن وابدأ ببناء مفرداتك.',
  'dontHaveAccount': 'ليس لديك حساب؟',
  'alreadyHaveAccount': 'لديك حساب بالفعل؟',
  'emailRequired': 'البريد الإلكتروني مطلوب',
  'invalidEmail': 'يرجى إدخال بريد إلكتروني صحيح.',
  'passwordRequired': 'كلمة المرور مطلوبة',
  'passwordTooShort': 'يجب ألا تقل كلمة المرور عن 6 أحرف',
  'nameRequired': 'الاسم مطلوب',
  'passwordsDoNotMatch': 'كلمتا المرور غير متطابقتين',
  'loginFailed': 'تعذّر تسجيل الدخول. حاول مرة أخرى.',
  'signUpFailed': 'تعذّر إنشاء الحساب. حاول مرة أخرى.',
  'emailAlreadyExists':
      'يوجد حساب بهذا البريد الإلكتروني بالفعل. جرّب تسجيل الدخول.',
  'invalidCredentials': 'بريد إلكتروني أو كلمة مرور غير صحيحة. حاول مرة أخرى.',
  'logoutConfirm': 'تسجيل الخروج؟',
  'logoutMessage': 'ستحتاج إلى تسجيل الدخول مرة أخرى للوصول إلى حسابك.',
  'account': 'الحساب',
  'wrongPassword': 'كلمة المرور غير صحيحة. حاول مرة أخرى.',
  'userNotFound': 'لا يوجد حساب بهذا البريد الإلكتروني. سجّل أولاً.',
  'weakPassword': 'كلمة المرور ضعيفة. استخدم كلمة مرور أقوى.',
  'operationNotAllowed': 'طريقة تسجيل الدخول هذه غير مفعّلة. حاول مرة أخرى.',
  'tooManyRequests': 'محاولات كثيرة. حاول مرة أخرى لاحقاً.',
  'requiresRecentLogin': 'يرجى تسجيل الدخول مرة أخرى لإتمام هذا الإجراء.',
  'userDisabled': 'تم تعطيل هذا الحساب. يرجى التواصل مع الدعم.',
};
